---
title: "L_Regression_9.3"
author: "Adriana RM"
date: "9/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Setting Reference Levels 
```{r}
#Change reference level for COVCLIN Trial To Yes

dft1 = dft1 %>% mutate(COVCLINTRIAL = relevel(COVCLINTRIAL, "Yes"))

# Changing reference level for RACEi to Non-Hispanc White

dft1 = dft1 %>% mutate(RACEi = relevel(RACEi,"Non-Hispanic White"))


```

## Logistic Regression Ungrouped RACEi

```{r}

logistic.model <- glm(COVCLINTRIAL ~ SEX + AGEi + factor(RACEi), data= dft1, family = 'binomial')

#Model Summary
summary(logistic.model)

```

```{r}
## Group RACEi according to:
# For categorizations, we combined race/ethnicity by the following hierarchy:
# ·         Hispanic (any Race)
# ·         Black
# ·         Asian/Pacific Islander 
# ·         non-Hispanic white (NHW)
# ·         Other (Includes American Indian and Alaskan Native)
# ·         Unable to determine

## Create New Race Ethnicity Variable: RACEgroup 

library(forcats)
dft1$RACEgroup <- fct_collapse(dft1$RACEi,
  UTD = "UTD",
  Other = "Native American",
  NHWhite = "Non-Hispanic White",
  Asian_PI = c("Asian", "Pacific Islander"),
  Black = "Non-Hispanic Black",
  Hispanic = "Hispanic"
)

```

## Logistic Model with Recommended Race Grouping
```{r}

#Set reference level to NHW in RACEgroup
dft1 = dft1 %>% mutate(RACEgroup = relevel(RACEgroup,"NHWhite"))

#Logistic Model 2
logistic.model2 <- glm(COVCLINTRIAL ~ SEX + AGEi + factor(RACEgroup), data= dft1, family = 'binomial')

#Model 2 Summary
summary(logistic.model2)

```
```{r}
##Model Accounting for Hospital Variability

logistic.model3 <- glm(COVCLINTRIAL ~ SEX + AGEi + factor(RACEgroup) + (1/SRC_FAC_ID), data= dft1, family = 'binomial')

summary(logistic.model3)

```
```{r}

# estimate the model and store results in m
m <- glmer(COVCLINTRIAL ~ SEX + AGEi + factor(RACEgroup) + (1 | SRC_FAC_ID ), data = dft1, family = binomial)


# print the mod
print(m, corr = FALSE)

```
li

