---
title: "Descriptives Covid_8.26"
output:
  html_document:
    df_print: paged
  html_notebook: default
  word_document: default
---
#Load Packages

```{r}
library(dplyr)
library(reshape2)
library(ggplot2)
library(esquisse)
library(haven)
library(broom)
library(SmartEDA)
library(summarytools)
library(stats)
library(kableExtra)
library(DataExplorer)
library(scales)
library(RColorBrewer)
library(ecm)
```

## Loading the Data
```{r Read Data, message=FALSE, warning=FALSE, include=FALSE}

#Read in data and save it in df object (original data for comparison)
dataFile = '/mnt/workspace/GWTG/COVID19/10-2020/limited/data/oct20_aha_covid19_cvd.sas7bdat'
formatsFile = '/mnt/workspace/scratchbucket/notebook/R_Python_windows_formats.sas7bcat'

## Assigning the dataframe to the df2nd object
df2nd <- haven::read_sas(dataFile, formatsFile)

dim(df2nd)

```

```{r}
#Print Unique Record ID

#To identify unique patients- use FACILITY_ID/FACILTY_DISPLAY_ID and PATIENT_DISPLAY_ID
#To identify unique records-use FACILITY_ID/FACILTY_DISPLAY_ID and PATIENT_DISPLAY_ID and CASE_ID

cat("\n Original: Hospital Counts, Unique Patient,\n")
dim(df2nd)
length(unique(df2nd$FACILITY_DISPLAY_ID))

#Number of Unique Patients
df2nd %>%
  count(FACILITY_DISPLAY_ID, PATIENT_DISPLAY_ID) %>% tally() 

#Number of patients with 2 or more duplicates
df2nd %>%
  count(FACILITY_DISPLAY_ID, PATIENT_DISPLAY_ID) %>%
  filter(n > 1) %>% tally() 

df2nd %>%
  count(FACILITY_DISPLAY_ID, PATIENT_DISPLAY_ID,CASE_ID) %>%
  tally() 





```

```{r}

cat("\n Missing COVCLINTRIAL \n")
#Fileter on  COVCLINTRIAL

df2 <-df2nd %>% filter(!is.na(COVCLINTRIAL))

#Number of Unique Patients
df2 %>%
  count(FACILITY_DISPLAY_ID, PATIENT_DISPLAY_ID) %>% tally() 

#Number of patients with 2 or more duplicates
df2 %>%
  count(FACILITY_DISPLAY_ID, PATIENT_DISPLAY_ID) %>%
  filter(n > 1) %>% tally() 

df2 %>%
  count(FACILITY_DISPLAY_ID, PATIENT_DISPLAY_ID,CASE_ID) %>%
  tally() 


```

```{r}
 df2$ADMDTi <- ymd(df2$ADMDT)

# df2 %>%
#   mutate(
#      COVCLINTRIAL_factored=as.numeric(factor(COVCLINTRIAL,levels=c('1','2'),labels=1:2)),
#      Datei=as.Date(ADMDTi, format= "%y/%m/%d")) %>%
#   group_by(FACILITY_DISPLAY_ID,PATIENT_DISPLAY_ID) %>%
#    filter(COVCLINTRIAL_factored == min(COVCLINTRIAL) & Datei == max(Datei) & !duplicated(ADMDT))


df2 <-df2 %>%
    arrange(FACILITY_DISPLAY_ID, desc(CASE_ID)) %>%
    group_by(FACILITY_DISPLAY_ID, PATIENT_DISPLAY_ID) %>%
    mutate(mxDate = if(any(COVCLINTRIAL == 1)) ADMDT[which.max(ADMDT)] else
         ADMDT[which.max(ADMDT)]) %>%
    filter(ADMDT == mxDate & !duplicated(ADMDT)) %>%
  ungroup
 
```


```{r}

dup_summary <- df2 %>% select(FACILITY_DISPLAY_ID,
                                  PATIENT_DISPLAY_ID, CASE_ID,
                                  COVCLINTRIAL, ADMDT) %>%
                           group_by(FACILITY_DISPLAY_ID,PATIENT_DISPLAY_ID) %>% 
                           summarise(n_repeats = length(PATIENT_DISPLAY_ID)) %>%
                           arrange(desc(n_repeats))

dup_summary
 

#Number of Patients and repeats  (not yet looking a records)

n_patients_per_dup_n  <- dup_summary %>% group_by(n_repeats) %>% 
                                          summarise(n_patients =n()) %>% 
                                          select(n_patients, n_repeats)
n_patients_per_dup_n

# #Check patient with 6 repeats 
# nuf <-filter(dup_df2,FACILITY_DISPLAY_ID == '85527' & PATIENT_DISPLAY_ID == "7.35001E+11" ) 
#%>% select(FACILITY_DISPLAY_ID, PATIENT_DISPLAY_ID, CASE_ID, ADMDT, COVCLINTRIAL)
# 
# nuf


n_distinct(df2$FACILITY_ID,df2$PATIENT_DISPLAY_ID) #at 15051
n_distinct(df2$FACILITY_ID,df2$PATIENT_DISPLAY_ID,df2$CASE_ID) # 15051

```



```{r}

#Number of rows with at least one repeating PATIENT_DISPLAY_ID and 
#number of unique repeating PATIENT_DISPLAY_IDs row(dup_df)

dim(dup_df2[duplicated(dup_df2$FACILITY_DISPLAY_ID, dup_df2$PATIENT_DISPLAY_ID, fromLast = TRUE),]) 
dim(dup_df2[duplicated(dup_df2$FACILITY_DISPLAY_ID, dup_df2$PATIENT_DISPLAY_ID),]) 

dup_summary <- dup_df2 %>% select(FACILITY_DISPLAY_ID,
                                  PATIENT_DISPLAY_ID, CASE_ID,
                                  COVCLINTRIAL, ADMDT) %>%
                           group_by(FACILITY_DISPLAY_ID,PATIENT_DISPLAY_ID) %>% 
                           summarise(n_repeats = length(PATIENT_DISPLAY_ID)) %>%
                           arrange(desc(n_repeats))

dup_summary
 
#Check patient with 6 repeats 
nuf <-filter(dup_df2,FACILITY_DISPLAY_ID == '85527' & PATIENT_DISPLAY_ID == "7.35001E+11" ) %>% select(FACILITY_DISPLAY_ID, PATIENT_DISPLAY_ID, CASE_ID, ADMDT, COVCLINTRIAL)

nuf

#Number of Patients and repeats  (not yet looking a records)

n_patients_per_dup_n  <- dup_summary %>% group_by(n_repeats) %>% 
                                          summarise(n_patients =n()) %>% 
                                          select(n_patients, n_repeats)
n_patients_per_dup_n

#Check whether these are actual repeats or different records...
```


```{r}
#Exclude NA's on COVCLINTRIAL
# 367 rows with NAs for COVCLIN Trail 

cat("\n Missing COVCLINTRIAL \n")
sum(is.na(dup_df2$COVCLINTRIAL))

# 367 rows with NAs for COVCLIN Trail 

filt_clintrial<- dup_df2 %>% dplyr::filter(!is.na(COVCLINTRIAL))

#Print Unique
cat("\n Complete COVCLINTRIAL Record: Patient,Records, Hospital Counts \n")

n_distinct(filt_clintrial$FACILITY_ID,filt2$PATIENT_DISPLAY_ID) 
# 15046 after filtering for NA's Covclintrail (15046...original 15392 vs 15399)
n_distinct(filt_clintrial$FACILITY_ID,filt2$PATIENT_DISPLAY_ID,filt2$CASE_ID) # 15301 (15668 vs 15673)
n_distinct(filt_clintrial$FACILITY_ID) #99 Hospitals

```

```{r}
fil_dup_sum <- filt_clintrial %>% select(FACILITY_DISPLAY_ID,
                                  PATIENT_DISPLAY_ID, CASE_ID,
                                  COVCLINTRIAL, ADMDT) %>%
                           group_by(FACILITY_DISPLAY_ID,PATIENT_DISPLAY_ID) %>% 
                           summarise(n_repeats = length(PATIENT_DISPLAY_ID)) %>%
                           arrange(desc(n_repeats))

fil_dup_sum
 
#Check patient with 6 repeats 
nuf <-filter(filt_clintrial,FACILITY_DISPLAY_ID == '85527' & PATIENT_DISPLAY_ID == "7.35001E+11" ) %>% select(FACILITY_DISPLAY_ID, PATIENT_DISPLAY_ID, CASE_ID, ADMDT, COVCLINTRIAL)

nuf

#Number of Patients and repeats  (not yet looking a records)

n_pt_per_dup_n  <- fil_dup_sum %>% group_by(n_repeats) %>% 
                                          summarise(n_patients =n()) %>% 
                                          select(n_patients, n_repeats)
n_pt_per_dup_n

#Check whether these are actual repeats or different records...
```
```{r}
library(ecm)
# Add an Accumulator Var for the times a PATIENT_DISPLAY_ID repeats 
df_drops <- filt_clintrial %>% group_by(FACILITY_DISPLAY_ID, PATIENT_DISPLAY_ID) %>%
                       mutate(DROPS = cumcount(PATIENT_DISPLAY_ID)) %>% 
                       select(PATIENT_DISPLAY_ID, COVCLINTRIAL, FACILITY_DISPLAY_ID,
                            CASE_ID, DROPS, everything()) %>% arrange(desc(DROPS))
df_drops
```

```{r}
#Selecting those with more than 1 repeat or "drop"

#this keeps the first appearance of the drop (as denoted by 1)
withrepeats <-df_drops %>% filter(DROPS > 1)
dim(withrepeats)

#Get drops=1 of records in withrepeats 

try1 <- semi_join(df_drops, withrepeats, by = c("FACILITY_DISPLAY_ID", "PATIENT_DISPLAY_ID"))

duplicados<-full_join(withrepeats,try1)

#TREAT withrepeats
#Keeps the Patients with latest Date and Covclintrial=1, and if equal data, keeps highest CASE_ID

library(lubridate)

testwr <-duplicados %>%
   mutate(ADMDT = ymd(ADMDT)) %>%
   arrange(FACILITY_DISPLAY_ID, desc(CASE_ID)) %>%
   group_by(FACILITY_DISPLAY_ID) %>% 
   mutate(mxDate = if(any(COVCLINTRIAL == 1)) ADMDT[which.max(ADMDT)] else 
        ADMDT[which.max(ADMDT)]) %>%
   filter(ADMDT == mxDate & !duplicated(ADMDT)) %>% 
  ungroup

testwr

dim(testwr)

droprows<-anti_join(duplicados, testwr, by= c("FACILITY_DISPLAY_ID","PATIENT_DISPLAY_ID", "CASE_ID"))

#Df with drops
drop_rows <- select(droprows,FACILITY_DISPLAY_ID,PATIENT_DISPLAY_ID, CASE_ID)
drop_rows

#Make drops into a vector 
vecdrops <- as.vector(drop_rows)
head(vecdrops)
```

```{r}
#Create Not In Operator
`%notin%` <- Negate(`%in%`)

#Filter from main fil_clintrial df based on drops 

cleandata<-anti_join(filt_clintrial, drop_rows,by= c("FACILITY_DISPLAY_ID","PATIENT_DISPLAY_ID", "CASE_ID"))


# prodf <- filt_clintrial[filt_clintrial$PATIENT_DISPLAY_ID %notin% vecdrops$PATIENT_DISPLAY_IDfilt_clintrial$CASE_ID %notin% vecdrops$CASE_ID | filt_clintrial$FACILITY_DISPLAY_ID %notin% vecdrops$FACILITY_DISPLAY_ID | , , drop = FALSE]
# 
# dim(prodf)

#Dropping the 195 repeats of patient with 196 repeats
#d2 <-ef[!(ef$PATIENT_DISPLAY_ID=="9.00064E+15004806"),]

##Check
length(unique(prodf$CASE_ID))
length(unique(prodf$PATIENT_DISPLAY_ID))
length(unique(prodf$FACILITY_DISPLAY_ID))

```

```{r}
fil_dup_sum <- cleandata %>% select(FACILITY_DISPLAY_ID,
                                  PATIENT_DISPLAY_ID, CASE_ID,
                                  COVCLINTRIAL, ADMDT) %>%
                           group_by(FACILITY_DISPLAY_ID,PATIENT_DISPLAY_ID) %>% 
                           summarise(n_repeats = length(PATIENT_DISPLAY_ID)) %>%
                           arrange(desc(n_repeats))

fil_dup_sum
 

#Number of Patients and repeats  (not yet looking a records)

n_pt_per_dup_n  <- fil_dup_sum %>% group_by(n_repeats) %>% 
                                          summarise(n_patients =n()) %>% 
                                          select(n_patients, n_repeats)
n_pt_per_dup_n


# #Check Individual PT with Repeats
# nuf <-filter(prodf,FACILITY_DISPLAY_ID == '16742' & PATIENT_DISPLAY_ID == "257946" ) %>% select(FACILITY_DISPLAY_ID, PATIENT_DISPLAY_ID, CASE_ID, ADMDT, COVCLINTRIAL)

#Check Duplicates One Last Time


```

##Select Working Variables and Add Labels

```{r Select Working Variables and Add Labels, include=FALSE}
#Select Working Variables and Exclude NAs in COVCLINTRIAL

library(dplyr)

dft1 <- df2 %>% dplyr::select(CASE_ID,PATIENT_DISPLAY_ID,FACILITY_DISPLAY_ID,
              SEX,AGEi,RACEi,BMIadmit,
              HGBADM, WBCADM, PLATELET,
              INITSCR, TROPADM,ANTIHYPRTNSV,
              LIPLOWTHRP,ANTIPLT, ANTICOAG,
              ANTIHYPRGLYM,DDMER, DISDATE, DSCHSTAT,
              TROPADM, INITSCR, COVCLINTRIAL,
              PATMANICU,ADMDT,DEATHDT,PSOURCE_01,
              PSOURCE_02,PSOURCE_03,PSOURCE_04,
              PSOURCE_05, PSOURCE_06, PSOURCE_07,
              PSOURCE_09, CARDARR, SHKMGMT_01,
              SHKMGMT_02, SHKMGMT_04, SHKMGMT_05,
              SHKMGMT_03, HOSPVENT, SCRUADM,
              TROPUADM, DDMERU, HGBUADM, WBCUADM,
              WEIGHTADMi, HEIGHTi,DOCUSYMP_12,ZIP, matches("MEDHISTO_")) %>%
      dplyr::filter(!is.na(COVCLINTRIAL))

#LABEL VARS

#Sex 

dft1$SEX <- factor(dft1$SEX, levels = c("1", "2"), 
                  labels = c("Male", "Female"))

#Covclintrial

dft1$COVCLINTRIAL <- factor(dft1$COVCLINTRIAL, levels = c("1", "2"),
                            labels =c( "Yes", "No"))

#RACEi is AHA's defition

dft1$RACEi <- factor(dft1$RACEi, levels = c("1", "2", "3", "4", "5", "6", "7"),
                  labels = c("Hispanic",
                             "Non-Hispanic Black",
                             "Native American",
                             "Asian",
                             "Pacific Islander",
                             "Non-Hispanic White",
                             "UTD"))
#Hispanic Ethnicity
# dft1$HISETHNI <- factor(dft1$HISETHNI, levels = c("1", "2"),
#                         labels = c("Yes", "No/UTD"))

#Label Med Histos
medhx<-select(dft1, DOCUSYMP_12,  matches('MEDHISTO')) 
names(medhx)

for (var in names(medhx)){
  dft1[[var]] <- factor(dft1[[var]], levels = c("0","1"),
                        labels = c("No", "Yes"))}
#Check
count=0
for (var in names(medhx)){
  str(filthosp[[var]])
  count = count + 1
  print(count)
}  

#Hospital Ventilation
dft1$HOSPVENT <- factor(dft1$HOSPVENT, levels = c("1", "2"), 
                  labels = c("Yes", "No"))

## Medications Prior To Admission

dft1$ANTIHYPRTNSV <- factor(dft1$ANTIHYPRTNSV, levels = c("1", "2"), 
                  labels = c("Yes", "No"))

dft1$LIPLOWTHRP <- factor(dft1$LIPLOWTHRP, levels = c("1", "2"), 
                  labels = c("Yes", "No/ND"))

dft1$ANTIPLT <- factor(dft1$ANTIPLT, levels = c("1", "2"), 
                  labels = c("Yes", "No/ND"))

dft1$ANTICOAG <- factor(dft1$ANTICOAG, levels = c("1", "2"), 
                  labels = c("Yes", "No/ND"))

dft1$ANTIHYPRGLYM <- factor(dft1$ANTIHYPRGLYM, levels = c("1", "2"), 
                  labels = c("Yes", "No/ND"))

dft1$PATMANICU <- factor(dft1$PATMANICU, levels =  c("1", "2"), 
                  labels = c("Yes", "No"))

table(dft1$PATMANICU)
## Factorize Payment Sources
psources<-names(select(dft1, matches('PSOURCE_0'))) 

for (var in psources) { 
  dft1[[var]]<- as.factor(dft1[[var]])}

#factorize region
# dft1$region <- as.factor(dft1$region)
# 
# dft1$Cerebrovasc_group <-as.factor(dft1$)

table(dft1$PATMANICU, useNA = "ifany")
```

```{r Recode and Combine Variables}

#Create age_group variable

dft1 <- dft1 %>% mutate(age_group = case_when(AGEi > 64 ~ '>64',
                                             AGEi >= 50 & AGEi <= 64 ~ '50-64',
                                             AGEi < 50 ~ '<50'))
#Create psource_group

dft1 <- dft1 %>% mutate(psource_group = case_when((is.na(PSOURCE_04) == TRUE) | (PSOURCE_09 == 1) ~ "Unknown",
  (PSOURCE_04 == 1) ~ "Self pay",
  (PSOURCE_03 == 1) | (PSOURCE_07 == 1) ~ "Other",
  (PSOURCE_05 == 1) ~ "Medicare",
  (PSOURCE_01 == 1) | (PSOURCE_02 == 1)|(PSOURCE_06 ==1) ~ "Medicaid"))

 
# Create Death Var with AHA Logic

dft1 <- dft1 %>% mutate(death = ifelse(!is.na(DISDATE) == TRUE & DSCHSTAT == 6 , 1, 0))
dft1$death <- as.factor(dft1$death)


# Discharge Data (DISDATE) is not missing and Discharge Status is 6 or "Expired" 

dft2<- dft1 %>% mutate(Covid_Sev = case_when(DSCHSTAT == 6 ~ "Level 1",
                                                  CARDARR == 1 ~ "Level 2",
                                                  SHKMGMT_01 == 1 ~ "Level 3",
                                                  SHKMGMT_02 == 1 ~ "Level 3",
                                                  SHKMGMT_04 == 1 ~ "Level 3",
                                                  SHKMGMT_05 == 1 ~ "Level 3",
                                                  SHKMGMT_03 == 1 ~ "Level 4",
                                                  HOSPVENT == 1 ~ "Level 5",
                                                  DSCHSTAT != 6 &
                                                  CARDARR != 1 &
                                                  SHKMGMT_01 != 1 &
                                                  SHKMGMT_02 != 1 &
                                                  SHKMGMT_04 != 1 &
                                                  SHKMGMT_05 != 1 &
                                                  SHKMGMT_03 != 1 &
                                                  HOSPVENT != 1 ~ "Level 6")) ## do else, or nested else 

dft2$Covid_Sev <- as.factor(dft2$Covid_Sev)

## Create New Race Ethnicity Variable: RACEgroup 

library(forcats)
dft1$RACEgroup <- fct_collapse(dft1$RACEi,
  UTD = "UTD",
  Other = "Native American",
  NHWhite = "Non-Hispanic White",
  Asian_PI = c("Asian", "Pacific Islander"),
  Black = "Non-Hispanic Black",
  Hispanic = "Hispanic"
)


#Compute BMI Variable

#WEIGHTADMi in Kg
#HEIGHTi in cm 
#peso (kg) / [estatura (m)]2 

dft1 <- dft1 %>% mutate(BMI = (WEIGHTADMi/((HEIGHTi/100)^2)))

dft1 <- dft1 %>% mutate(BMIgroup = case_when(BMI < 18.5 ~ 'Underweight',
                                             BMI >= 18.5 & BMI < 25.0 ~ 'Normal',
                                             BMI >= 25.0 & BMI < 30.0 ~ 'Overweight',
                                             BMI >=30.0 ~ 'Obese'))

dft1$BMIgroup <- as.factor(dft1$BMIgroup)


#948 missing BMI values due to either Weight or Height not documented
summary(dft1$BMI)
summary(dft1$WEIGHTADMi)
table(is.na(dft1$HEIGHTi))
table(is.na(dft1$WEIGHTADMi))                    
table(is.na(dft1$BMI))
filter(dft1, BMI >80)
hist(dft1$BMIadmit)
hist(dft1$BMI)


#Combine Cerebrovascular Disease

dft1 <-dft1 %>% mutate(Cerebrovasc_group = case_when((MEDHISTO_05 == "Yes") | (MEDHISTO_06 == "Yes") | (MEDHISTO_04 == "Yes") ~ "Yes",
                                              (MEDHISTO_04 == "No")| (MEDHISTO_05 == "No") | (MEDHISTO_06 == "No") ~ "No"))

##199 had 3 medical histories 
##  MEDHISTO_04 is a catch all for both? 

filter(dft1, MEDHISTO_04 == "Yes" & MEDHISTO_05 == "Yes" | MEDHISTO_06 == "Yes")
filter(dft1, MEDHISTO_04 == "Yes" | MEDHISTO_05 == "Yes" | MEDHISTO_06 == "Yes")
filter(dft1, MEDHISTO_04 == "Yes")

table(dft1$Cerebrovasc_group)


# Combine atrial fibrillation/flutter

dft1 <-dft1 %>% mutate(fibandflutter = case_when( (MEDHISTO_01 == "Yes") | (MEDHISTO_02 == "Yes") ~ "Yes",
                                                  (MEDHISTO_01 == "No")| (MEDHISTO_02 == "No") ~ "No"))

table(dft1$MEDHISTO_01)                                                                                                 
table(dft1$MEDHISTO_02)
table(dft1$fibandflutter)    

# 44 patients had both 
filter(dft1, MEDHISTO_01 == "Yes" & MEDHISTO_02 == "Yes")
                                              
 
# Combine DVT/pulmonary embolism

dft1 <-dft1 %>% mutate(dvt_pe = case_when( (MEDHISTO_19 == "Yes") | (MEDHISTO_27== "Yes") ~ "Yes",
                                                  (MEDHISTO_19 == "No")| (MEDHISTO_27 == "No") ~ "No"))

table(dft1$MEDHISTO_19)
table(dft1$MEDHISTO_27)
table(dft1$dvt_pe)

filter(dft1, MEDHISTO_19 == "Yes" & MEDHISTO_27 == "Yes")

# Combine smoking/vaping


dft1 <-dft1 %>% mutate(smo_vape = case_when( (MEDHISTO_20 == "Yes") | (MEDHISTO_21== "Yes") ~ "Yes",
                                                  (MEDHISTO_20 == "No")| (MEDHISTO_21 == "No") ~ "No"))      
table(dft1$MEDHISTO_20)
table(dft1$MEDHISTO_21)
table(dft1$smo_vape)

filter(dft1, MEDHISTO_20 == "Yes" | MEDHISTO_21 == "Yes")


new_vars<-select(dft1, Cerebrovasc_group,smo_vape, dvt_pe,fibandflutter) 
names(new_vars)

for (var in names(new_vars)){
  dft1[[var]] <- factor(dft1[[var]], levels = c("No","Yes"),
                        labels = c("No", "Yes"))}

table(dft1$Cerebrovasc_group)

contrasts(dft1$ANTIHYPRTNSV)
contrasts(dft1$DOCUSYMP_12)
contrasts(dft1$HOSPVENT)
```



```{r}
## Group Dates by Before March and then Each Following Month as continuos

library(lubridate)

#Extracted Admission Date Month into "admmonth" var
dft1$admmonth <- month(dft1$ADMDT)

#Summarize Counts by Month
dft1 %>% group_by(admmonth) %>% tally()  

#Convert admmonth as factor
dft1$admmonth <- as.factor(dft1$admmonth)

#Create var "month_continuous based on admmonth
dft1 <-dft1 %>% mutate(month_cont = case_when(admmonth == "12" ~ 0, 
                                              admmonth == "1" ~ 0,
                                              admmonth == "2" ~ 0,
                                              admmonth == "3" ~ 1,
                                              admmonth == "4" ~ 2,
                                              admmonth == "5" ~ 3,
                                              admmonth == "6" ~ 4,
                                              admmonth == "7" ~ 5,
                                              admmonth == "8" ~ 6,
                                              admmonth == "9" ~ 7))
        

table(as.factor(dft1$month_cont))
head(dft1$month_cont)
head(dft1$ADMDT)

```

```{r}
#ZIP Code Mapping
#install.packages("usa")
#install.packages("zipcode")
library(usa)
library(zipcode)

##Select zipcode, state, and region
zip_states<-select(zipcodes, zip, state)
dft1$cleanzips <- clean.zipcodes(dft1$ZIP)
head(dft1$cleanzips)

#Keep the 5 fisrt digits of Zip Code
dft1$cleanerzips<-sapply(dft1$cleanzips, strtrim, width = 5)
head(dft1$cleanerzips)

##cleaner has cleanerzips as colname 
#JOIN BY ZIP STATE and Region Variables 
dft1 <-left_join(dft1, zip_states, by = c("cleanerzips" = "zip") )
dft1 %>% group_by(cleanerzips) %>% count(is.na(cleanerzips))
table(is.na(dft1$cleanerzips))

names(dft1)
# 500 are NA
#JOIN State Abbreviation(state.abb) to  and Region 
head(usa::states)

#JOIN BY ABBREVIATION to df with Region
dft1<-left_join(dft1, states, by = c("state" = "abb") )

#check
names(dft1)
str(dft1$cleanerzips)

dft1 %>% select(FACILITY_DISPLAY_ID, PATIENT_DISPLAY_ID, cleanerzips) %>% filter(cleanerzips == "NA")

dft1 %>% select(FACILITY_DISPLAY_ID, PATIENT_DISPLAY_ID, cleanerzips) %>% filter(cleanerzips == "NA" | cleanerzips == "NULL")



dft1$region <-as.factor(dft1$region)
```




```{r}

## Converting Units for DDMER, Creatinine,and Troponin

hist(df2nd$DDMERU, plot = TRUE)
hist(df2nd$TROPUADM, plot = TRUE)
hist(df2nd$SCRUADM, plot =TRUE)

#Convert DDMER factors 2 (u/mL) and 3 (ug/mL) to 1 (ng/mL)

dft1<- dft1 %>% mutate(DDMER_T = case_when(DDMERU == 1 ~ (DDMER*1),
          DDMERU == 2 ~ (DDMER*1000),
          DDMERU == 3 ~ (DDMER*1000)))

hist(dft1$DDMERU)
hist(dft1$DDMER_T)
 
filter(dft1, DDMER_T <= 10000)



```

```{r}
# Convert Creatinine units factor 2 (umol/L) to factor 1 (mg/dL)
dft1<- dft1 %>% mutate(CREATININE_T = case_when(SCRUADM == 1 ~ (INITSCR*1),
          SCRUADM == 2 ~ (INITSCR/88.42)))

table(dft1$SCRUADM)
hist(dft1$INITSCR)
hist(dft1$CREATININE_T)
summary(dft1$CREATININE_T)

hist(dft1$INITSCR, breaks = 200)
hist(dft1$CREATININE_T, breaks = 200)


# 17 patients

dft1 %>% select(SCRUADM, INITSCR, CREATININE_T) %>% filter (CREATININE_T > 20)


```

```{r}

#13 p patients with over 100 Troponin --- Keep them
#Convert Troponin factors 2 (ug/L) and 3(ng/L) to 1 (ng/mL)

dft1<- dft1 %>% mutate(TROPOADM_t = case_when(TROPUADM == 1 ~ (TROPADM*1),
          TROPUADM == 2 ~ (TROPADM*1),
          TROPUADM == 3 ~ (TROPADM*0.001)))

hist(dft1$TROPADM)
hist(dft1$TROPOADM_t)

summary(dft1$TROPOADM_t)

hist(dft1$TROPADM, breaks = 200)
hist(dft1$TROPOADM_t, breaks = 200)

#10 patients with over 100 Troponin --- Keep them

dft1<- dft1 %>% mutate(TROPOADM_t = case_when(TROPUADM == 1 ~ (TROPADM*1),
          TROPUADM == 2 ~ (TROPADM*1),
          TROPUADM == 3 ~ (TROPADM*0.001)))


dft1 %>% select(TROPADM, TROPUADM, TROPOADM_t) %>% filter (TROPOADM_t > 0.90)

#Hemoglobin
```

```{r Histograms}

# Plotting Histograms of Continuous Vars Using Data Explorer
# 
# dft1 %>% select(AGEi, DDMER, HGBADM, INITSCR, PLATELET, TROPADM, WBCADM) %>% plot_histogram(geom_histogram_args = list(binwidth = .3, col ="black", size = 3))

#Hemoglobin 

hist(dft1$HGBADM,breaks = 300, plot = TRUE)
dft1 %>% filter ( HGBADM > 50)

#CHECK UNITS

table(df2nd$HGBUADM)


#WBC
hist(dft1$WBCADM,breaks= 200, plot = TRUE) 
#Use unique to see unique values in the variable
#May be a conversion factor issue One patient at 7387.0 
# Fema…    38 Hisp…   13.3   7387      219 

#
hist(dft1$PLATELET)
# Outliers: 3 patients with over 3000  
dft1 %>% filter ( PLATELET > 800)

#Creatinine 
hist(dft1$INITSCR, breaks= 200)
#11 patiens with initscr >20
#dft1 %>% filter ( INITSCR > 20)

#Troponin
hist(dft1$TROPADM, breaks = 200)
#10 patients with over 100 Troponin --- Keep them 

#DDMER Prot
hist(dft1$DDMER, breaks = 80, plot = TRUE)



```


