---
title: "T1"
author: "Adriana RM"
date: "9/14/2020"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r
```


```{r}
library(arsenal)

#Select Working Variables and Exclude NAs in COVCLINTRIAL





library(dplyr)

dft1 <- ef2 %>% dplyr::select(CASE_ID,SEX,AGEi,RACEi,
                               HGBADM, WBCADM, PLATELET,
                               INITSCR, TROPADM,ANTIHYPRTNSV,
                               LIPLOWTHRP,ANTIPLT, ANTICOAG,
                               ANTIHYPRGLYM, HISETHNI,DDMER,
                               TROPADM, INITSCR, COVCLINTRIAL,
                               MEDHISTO_01, MEDHISTO_02, MEDHISTO_08,
                               MEDHISTO_09,MEDHISTO_11, MEDHISTO_12,
                               PATMANICUDT,PATMANICU, SRC_FAC_ID,
                               DISDATE,DSCHSTAT, ADMDT,DEATHDT,PSOURCE_01,
                               PSOURCE_02,PSOURCE_03,PSOURCE_04,
                               PSOURCE_05, PSOURCE_06, PSOURCE_07,
                               PSOURCE_09, CARDARR, SHKMGMT_01,
                               SHKMGMT_02, SHKMGMT_04, SHKMGMT_05, SHKMGMT_03, 
                               HOSPVENT, SCRUADM,TROPUADM, DDMERU, HGBUADM,
                              WBCUADM) %>% ## CONTINUE ADD SEVERETIY VARS
                  dplyr::filter(!is.na(COVCLINTRIAL))

                                
#Adding Labels for Factor Vars

#Sex 

dft1$SEX <- factor(dft1$SEX, levels = c("1", "2"), 
                  labels = c("Male", "Female"))

#Covclintrial

dft1$COVCLINTRIAL <- factor(dft1$COVCLINTRIAL, levels = c("1", "2"),
                            labels =c( "Yes", "No"))

#RACEi is AHA's defition

dft1$RACEi <- factor(dft1$RACEi, levels = c("1", "2", "3", "4", "5", "6", "7"),
                  labels = c("Hispanic",
                             "Non-Hispanic Black",
                             "Native American",
                             "Asian",
                             "Pacific Islander",
                             "Non-Hispanic White",
                             "UTD"))
#Hispanic Ethnicity
dft1$HISETHNI <- factor(dft1$HISETHNI, levels = c("1", "2"),
                        labels = c("Yes", "No/UTD"))

#Atrial Fibrilation
dft1$MEDHISTO_01 <- factor(dft1$MEDHISTO_01, levels = c("0", "1"), 
                  labels = c("No", "Yes"))

#Atrial Flutter
dft1$MEDHISTO_02 <- factor(dft1$MEDHISTO_02, levels = c("0", "1"), 
                  labels = c("No", "Yes"))

#Diabetes Mellitus  
dft1$MEDHISTO_08 <- factor(dft1$MEDHISTO_08, levels = c("0", "1"), 
                  labels = c("No", "Yes"))

#Dyslipidemia
dft1$MEDHISTO_09 <- factor(dft1$MEDHISTO_09, levels = c("0", "1"), 
                  labels = c("No", "Yes"))
#Heart Failure
dft1$MEDHISTO_11 <- factor(dft1$MEDHISTO_11, levels = c("0", "1"), 
                  labels = c("No", "Yes"))
#Hypertension
dft1$MEDHISTO_12 <- factor(dft1$MEDHISTO_12, levels = c("0", "1"), 
                  labels = c("No", "Yes"))

## Medications Prior To Admission

dft1$ANTIHYPRTNSV <- factor(dft1$ANTIHYPRTNSV, levels = c("1", "2"), 
                  labels = c("Yes", "No"))

dft1$LIPLOWTHRP <- factor(dft1$LIPLOWTHRP, levels = c("1", "2"), 
                  labels = c("Yes", "No/ND"))

dft1$ANTIPLT <- factor(dft1$ANTIPLT, levels = c("1", "2"), 
                  labels = c("Yes", "No/ND"))

dft1$ANTICOAG <- factor(dft1$ANTICOAG, levels = c("1", "2"), 
                  labels = c("Yes", "No/ND"))


dft1$ANTIHYPRGLYM <- factor(dft1$ANTIHYPRGLYM, levels = c("1", "2"), 
                  labels = c("Yes", "No/ND"))

dft1$PATMANICU <- as.factor(dft1$PATMANICU)

## Payment Sources
dft1$PSOURCE_01 <- as.factor(dft1$PSOURCE_01)
dft1$PSOURCE_02 <- as.factor(dft1$PSOURCE_02)
dft1$PSOURCE_03 <- as.factor(dft1$PSOURCE_03)
dft1$PSOURCE_04 <- as.factor(dft1$PSOURCE_04)
dft1$PSOURCE_05 <- as.factor(dft1$PSOURCE_05)
dft1$PSOURCE_06 <- as.factor(dft1$PSOURCE_06)
dft1$PSOURCE_07 <- as.factor(dft1$PSOURCE_07)
dft1$PSOURCE_09 <- as.factor(dft1$PSOURCE_09)


```

```{r}
#Create age_group variable

dft1 <- dft1 %>% mutate(age_group = case_when(AGEi > 64 ~ '>64',
                                             AGEi >= 50 & AGEi <= 64 ~ '50-64',
                                             AGEi < 50 ~ '<50'))
#Create psource_grouped

table(dft1$PSOURCE_01)
table(dft1$PSOURCE_02)
table(dft1$PSOURCE_06)

dft1 <- dft1 %>% mutate(psource_group = case_when((is.na(PSOURCE_04) == TRUE) | (PSOURCE_09 == 1) ~ "Unknown",
  (PSOURCE_04 == 1) ~ "Self pay",
  (PSOURCE_03 == 1) | (PSOURCE_07 == 1) ~ "Other",
  (PSOURCE_05 == 1) ~ "Medicare",
  (PSOURCE_01 == 1) | (PSOURCE_02 == 1)|(PSOURCE_06 ==1) ~ "Medicaid"))

# Create Death Vars with AHA Logic

dft1 <- dft1 %>% mutate(death = ifelse(!is.na(DISDATE) == TRUE & DSCHSTAT == 6 , 1, 0))
dft1$death <- as.factor(dft1$death)


# Discharge Data (DISDATE) is not missing and Discharge Status is 6 or "Expired" 

# dft2<- dft1 %>% mutate(Covid_Sev = case_when(DSCHSTAT == 6 ~ "Level 1",
#                                                   CARDARR == 1 ~ "Level 2",
#                                                   SHKMGMT_01 == 1 ~ "Level 3",
#                                                   SHKMGMT_02 == 1 ~ "Level 3",
#                                                   SHKMGMT_04 == 1 ~ "Level 3",
#                                                   SHKMGMT_05 == 1 ~ "Level 3",
#                                                   SHKMGMT_03 == 1 ~ "Level 4",
#                                                   HOSPVENT == 1 ~ "Level 5",
#                                                   DSCHSTAT != 6 &
#                                                   CARDARR != 1 &
#                                                   SHKMGMT_01 != 1 &
#                                                   SHKMGMT_02 != 1 &
#                                                   SHKMGMT_04 != 1 &
#                                                   SHKMGMT_05 != 1 &
#                                                   SHKMGMT_03 != 1 &
#                                                   HOSPVENT != 1 ~ "Level 6")) ## do else, or nested else 

dft2$Covid_Sev <- as.factor(dft2$Covid_Sev)

## Create New Race Ethnicity Variable: RACEgroup 

library(forcats)
dft1$RACEgroup <- fct_collapse(dft1$RACEi,
  UTD = "UTD",
  Other = "Native American",
  NHWhite = "Non-Hispanic White",
  Asian_PI = c("Asian", "Pacific Islander"),
  Black = "Non-Hispanic Black",
  Hispanic = "Hispanic"
)

```


```{r}

### Installing Table1 package from E Wozniak

#install_github("emwozniak/Table1")
library(Table1)


t1 <- make.table(dat  = dft1,
           strat        = "COVCLINTRIAL",
           cat.varlist  = c("SEX",
                             "RACEi",
                            "HISETHNI",
                            "age_group",
                            "psource_group",
                            "MEDHISTO_01",
                            "MEDHISTO_02",
                            "MEDHISTO_08",
                            "MEDHISTO_09",
                            "MEDHISTO_11",
                            "MEDHISTO_12",
                             "ANTIHYPRTNSV",
                            "LIPLOWTHRP",
                            "ANTIPLT",
                            "ANTICOAG",
                            "ANTIHYPRGLYM", 
                            "PATMANICU",
                            "death"),
           cat.header   = c("Sex",
                            "Race",
                            "Hispanic Ethnicity",
                            "Age Group",
                            "Payment Source",
                            "Atrial Fibrilation",
                            "Atrial Flutter",
                            "Diabetes Mellitus",
                            "Dyslipidemia", 
                            "Heart Failure",
                            "Hypertension",
                             "Antihypertensive", 
                            "Lipid-lowering Therapy",
                            "Antiplatelet",
                            "Anticoagulant",
                            "Anti-Hyperglycemic",
                            "Managed in ICU",
                            "Death"),
           cat.rmstat   = list(c("row"), c("col")),
           cat.ptype    = "chisq",
           cont.varlist = c("AGEi",
                            # "HGBADM",
                            # "WBCADM",
                            # "PLATELET",
                            # "INITSCR",
                            # "TROPADM",
                            # "DDMER",
                            "DISDATE"),
           cont.header =  c("Age", 
                            # "Hemoglobin",
                            # "WBC",
                            # "Platelet",
                            # "Creatinine", 
                            # "Troponin",
                            # "D-dimer",
                            "Length of Hospitalization"),
           cont.ptype   = c("wilcox"),
           colnames     = c("Variable", "Enrolled", "Not Enrolled", "Overall", "P-value"),output = "html")

t1

```


```{r eval=FALSE, include=FALSE}
#Using Arsenal
library(arsenal)
library(magrittr)
tmpdir <- tempdir()
                           

#Add Labels

dft1$psour

labels(dft1)  <- c( AGEi = 'Age', SEX = "Sex",
                    age_group = "Age Group", RACEi = "Race/Ethnicity",
                    HISETHNI = "Hispanic Ethnicity", psource_group = "Payment Source",
                    MEDHISTO_01 = "Atrial Fibrilation",
                    MEDHISTO_02 = "Atrial Flutter",
                    MEDHISTO_08 = "Diabetes Mellitus",
                    MEDHISTO_09 = "Dyslipidemia",
                    MEDHISTO_11 = "Heart Failure",
                    MEDHISTO_12 = "Hypertension",
                    ANTIHYPRTNSV = "Antihypertensive",
                    LIPLOWTHRP = "Lipid-lowering Therapy",
                    ANTIPLT = "Antiplatelet",
                    ANTICOAG = "Anticoagulant",
                    ANTIHYPRGLYM = "Anti-Hyperglycemic", 
                    PATMANICU = "Managed in ICU",
                    death = "In-Hospital Death")

tabla <- select(dft1, -c(CASE_ID, PATIENT_ID, SRC_FAC_ID, t1, TROPADM, - TROPUADM, HGBADM, WBCADM, PLATELET, INITSCR, TROPADM,DDMERU, DDMER, SCRUADM,WBCUADM, PSOURCE_01, PSOURCE_02,PSOURCE_03,PSOURCE_04,PSOURCE_05,PSOURCE_07, PSOURCE_09,
                         DISDATE,DSCHSTAT, ADMDT,DEATHDT,PSOURCE_01,
                               PSOURCE_02,PSOURCE_03,PSOURCE_04,
                               PSOURCE_05, PSOURCE_06, PSOURCE_07,
                               PSOURCE_09, CARDARR, SHKMGMT_01,
                               SHKMGMT_02, SHKMGMT_04, SHKMGMT_05, SHKMGMT_03, 
                               HOSPVENT, SCRUADM,TROPUADM, DDMERU, HGBUADM,
                              WBCUADM, RACEgroup, PATMANICUDT))

table_1 <-tableby(COVCLINTRIAL ~ ., data = tabla)

latabla<-summary(table_1, title = "Table 1", pfootnote = TRUE, digits=3, digits.test=2, nsmall.pct=1)


write2word(
  latabla, paste0(tmpdir, "/test.tableby.doc"), quiet = TRUE,
  title = "My table 1",      # passed to summary.tableby
  total = FALSE                 # passed to summary.tableby
)


```

```{r}

```

