---
title: "Visualizations"
author: "Adriana RM"
date: "5/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r cars}
#Visualizing the Data
#Age for the entire sample
ggplot(dft1) +
 aes(x = AGEi) +
 geom_histogram(bins = 100L, fill = "#6dcd59") +
 labs(x = "Age", y = "Count") +
 theme_classic()

```


```{r Vis (age/sex) in Enrolled vs Not Enrolled, echo=FALSE}
#Age and Sex comparison Enrolled vs Not-Enrolled

dft1 %>%
 filter(!is.na(SEX)) %>%
 filter(!is.na(AGEi)) %>%
 filter(!is.na(COVCLINTRIAL)) %>%
 ggplot() +
 aes(x = AGEi, fill = SEX) +
 geom_histogram(bins = 18L, position = "dodge") +
 scale_fill_hue() +
 labs(x = "Age", y = "Count", title = "Enrolled/Not Enrolled", fill = "Sex") +
 theme_classic() +
 facet_wrap(vars(COVCLINTRIAL), scales = "free_y")

```
#Visualizing

```{r Race Comparison - Enrolled vs Not Enrolled, echo=FALSE}

library(dplyr)
library(ggplot2)

melted<-melt(dft1$RACEi, dft1$COVCLINTRIAL, id=PATIENT_ID )

#Manipulating DAta With Denominator  

dat <-dft1 %>%
  select(RACEi, COVCLINTRIAL) %>%
  tidyr::gather(RACEi, COVCLINTRIAL, na.rm = FALSE, convert = FALSE, factor_key = FALSE) %>%
  count(RACEi, COVCLINTRIAL) %>%
  group_by(COVCLINTRIAL) %>%
  mutate(percent = (n/sum(n) * 100)) %>%
           mutate (rounded = round(percent, 1))

dat

#With Denominator

dft1 %>%
  group_by(RACEi, COVCLINTRIAL) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n)) %>%
  mutate(percent = (freq*100))

byrace<-dft1 %>%
  group_by(RACEi, COVCLINTRIAL) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n)) %>%
  mutate(percent = (freq*100), rounded = round(percent,1))

# byrace2<- dft1 %>%
#   filter(!(RACEi == "UTD")) %>%
#   mutate(raceplot = fct_collapse(RACEi,
#   Asian = "Asian",
#   NHWhite = "Non-Hispanic White",
#   NA_PI = c("Native American", "Pacific Islander"),
#   Black = "Non-Hispanic Black",
#   Hispanic = "Hispanic"))%>%
#   group_by(raceplot, COVCLINTRIAL) %>%
#   summarise(n = n()) %>%
#   mutate(freq = n / sum(n)) %>%
#   mutate(percent = (freq*100), rounded = round(percent,1))

byrace2<- dft1 %>%
  filter(!(RACEgroup == "UTD"))%>%
  group_by(RACEgroup, COVCLINTRIAL) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n)) %>%
  mutate(percent = (freq*100), rounded = round(percent,1))

byrace2
 
# sink("output.txt")
# byrace
# sink()
```

```{r}
# #PLOT
# ggplot(dat, aes(RACEi, percent, fill = COVCLINTRIAL)) + 
#     geom_col(position = "stack") + 
#   labs(x = "Race", y = "Percentage",
#        title = "Percentage of Patients Enrolled/Not Enrolled in Clinical Trials by Race",
#        fill = "Enrolled") + scale_y_continuous(limits = c(0, 100), breaks = seq(0, 100, by = 25)) +
#    geom_label(aes( label = "rounded",
#                 y= "rounded",
#            position = "stack",
#            vjust = 0.5))+
#   theme_classic() +
#   coord_flip()
# 
#  aes(x = reorder(Name, -Number), Number)
# 
# #Plot 2
#  png("myplot.png")
#  
p1 <- ggplot(data = byrace2, aes(y= percent, x= reorder(RACEgroup, -rounded), fill=COVCLINTRIAL)) + 
   geom_bar(stat="identity", width = 0.8) + 
   ggtitle("Figure 1. Percentage of Enrollment in Clinical Trials") +
   xlab('Race/Ethnicity') + ylab('Proportion (%) of All Enrolled Patients') +
   geom_text(aes(x = RACEgroup ,label = paste0(rounded, '%')), 
              colour = 'white',
              size= 3,
              position=position_stack(vjust=0.5)) + 
   labs(fill='Enrolled') +
   theme_classic() + 
   coord_flip()
 
p1

  
# file1 <- tempfile("file1", fileext = ".png")
# save_plot(file1, p1)
# View(file1)

# PLot Percentage of Enrollment by Race/Ethnicity
library(sjPlot)
library(ggplot2)

byrace2<-byrace2 %>% group_by(RACEgroup) %>% mutate(Totals= (sum(n)))

p2 <- byrace2 %>% filter((!(COVCLINTRIAL == "No"))) %>% ggplot(aes(y= percent, x= reorder(RACEgroup, -percent), fill=COVCLINTRIAL))+ 
  geom_bar(stat="identity", width = 0.8) + 
  ggtitle("Figure 1.Enrollment in Clinical Trials by Race/Ethnicity") +
  xlab('Race/Ethnicity') + ylab('Proportion (%) of Each Race/Ethnicity\nClassified as Enrolled in Clinical Trials') +
   geom_text(aes(x = RACEgroup, label = paste0(rounded, '%')), 
             colour = 'white',
             size= 2.7,
             position=position_stack(vjust=0.5)) +
  labs(fill='Enrolled')+
  scale_x_discrete(labels=c("Asian_PI" = "Asian and \n Pacific Islander \n n=716",
                            "Other" = "Native American \n n=67",
                            "Hispanic" = "Hispanic \n n=4,225",
                            "NHWhite" = "Non-Hispanic \n White \n n=5,159 ",
                            "Black" = "Non-Hispanic \n Black \n n=3,909")) +
    scale_y_continuous(limits=c(0,25))+
  theme_classic(base_size = 16) + 
  theme(legend.position = "none")


p2

ggsave("fig1_revised_may_2021.png")



head(byrace2)


#### Second Option

p3 <- byrace2 %>% filter((!(COVCLINTRIAL == "No"))) %>% 
  ggplot(aes(y= percent, x= reorder(RACEgroup, -percent), fill=COVCLINTRIAL))+ 
  geom_bar(stat="identity", width = 0.8) + 
  ggtitle("Figure 1.Percentage of Enrollment in Clinical Trials") +
  xlab('Race/Ethnicity') + ylab('Percentage') +
  geom_text(aes(x = RACEgroup, label = paste0(rounded), 
             colour = 'white',
             size= 2.7,
             position=position_stack(vjust=0.5))) +
  labs(fill='Enrolled')+
  scale_x_discrete(labels=c("Asian_PI" = "Asian and \n Pacific Islander",
                            "Other" = "Native American",
                            "Hispanic" = "Hispanic",
                            "NHWhite" = "Non-Hispanic \n White",
                            "Black" = "Non-Hispanic \n Black")) +
   scale_y_continuous(limits=c(0,25))+
   theme_classic(base_size = 16) 

p3

ggsave("fig1_n_only.png")


file <- tempfile("file1", fileext = ".png")
set_null_device("png")
save_plot(file,p2)
View(file)

```



```{r}

p3 <- byrace2 %>% filter((!(COVCLINTRIAL == "No"))) %>% ggplot(aes(y= percent, x= reorder(RACEgr, -percent), fill=COVCLINTRIAL)) +
  geom_bar(stat="identity", width = 0.8) +
  ggtitle("Figure 1. Percentage of Enrollment in Clinical Trials") +
  xlab('Race/Ethnicity') + ylab('Percentage') +
   geom_text(aes(x = raceplot, label = paste0(rounded, '%')),
             colour = 'white',
             size= 2.7,
             position=position_stack(vjust=0.5)) +
  labs(fill='Enrolled') +
  scale_y_continuous(limits=c(0,25))+
  theme(axis.text.x = element_text(size=14)) + 
  theme_classic()
  
p3

library(sjPlot)
file2 <- tempfile("file2", fileext = ".png")
save_plot(file2, p3)
View(file2)

```

```{r}
#PLot 2 with Labels 

#Print Dimensions
hist(cleandata$ADMDT, breaks = "month", freq = TRUE)

```

```{r}
##Histogram with ggplot2 
# 
cleandata$adate<-ymd(cleandata$ADMDT)
dft1$adate<- ymd(cleandata$ADMDT)
 
 
cleandata$ddate <- ymd(cleandata$DISDATE)
dft1$ddate <- ymd_hms(cleandata$DISDATE)
 
library(scales)
library(ggplot2)
ggplot(dft1, aes(x=adate, fill=COVCLINTRIAL)) + 
   stat_bin(binwidth=1, position="identity") + 
   scale_x_date(breaks=date_breaks(width="1 month"))
 
 
library(dplyr)
library(ggplot2)
 
#plot OVerall Admission Date
dft1 %>%
  filter(adate >= "2020-01-03" & adate <= "2020-09-25") %>%
  ggplot() +
#  aes(x = adate) +
#  geom_histogram(bins = 31L, fill = "#bd3786") +
#  labs(x = "Admission Date (2020)", y = "Count", title = "Frequency Count - Admission Dates") +
#  theme_minimal()
# 
# #Admission date Grouped by Covclintrial  #Binning changes 
# ggplot(dft1) +
#  aes(x = adate, fill = COVCLINTRIAL) +
#  geom_bar(position = "dodge") +
#  scale_fill_hue() +
#  labs(x = "Admission Date (2020)", y = "Count", title = "Frequency Count - Admission Dates") +
#  theme_minimal()
# 
# #With 1day for Bin
# library(scales)
# ggplot(dft1,aes(x=ddate, group=COVCLINTRIAL, fill=COVCLINTRIAL))+
#  stat_bin(binwidth=1, alpha=0.5,
#  position="identity") + theme_bw()+
#  xlab("Admission Date")+
#  ylab("Count")+
#  scale_x_date(breaks=date_breaks("1 month"), labels=date_format("%b %y")) 
# ```


```{r}

# library(esquisse)
# library(ggplot2)
# 
# ggplot(dft1) +
#  aes(x = RACEgroup, fill = RACEgroup) +
#  geom_bar(aes(y = (..count..)/sum(..count..)), position = "dodge") +
#  scale_fill_hue() +
#  labs(x = "Race", y = "%", title = "Enrolled vs Not Enrolled in Clinical Trials by Race") +
#  theme_classic() + scale_y_continuous(labels = scales::percent_format(accuracy=1.000)) +
#  scale_y_continuous(limits = c(0, 0.4), breaks = seq(0, 0.4, by = 0.05), labels = scales::percent_format(accuracy=1.00)) +
#  theme(legend.position = "none") +
#  facet_wrap(vars(COVCLINTRIAL))

# ggplot(dft1) +
#  aes(x = COVCLINTRIAL, fill = RACEgroup, group = RACEgroup) +
#   geom_bar(aes(y = (..count..)/sum(..count..)), position = "dodge") +
#  scale_fill_hue() +
#  labs(x = "Enrolled", y = "%", title = "Enrolled vs Not Enrolled in Clinical Trials by Race") +
#  theme_classic() +
#  scale_y_continuous(limits = c(0, 0.4), breaks = seq(0,0.4, by = 0.05), labels = scales::percent_format(accuracy=1.00)) +
#  theme(legend.position = "none") +
#  facet_wrap(vars(RACEgroup))

```


```{r}
library(ggplot2)
# 
# ggplot(dft1) +
#  aes(x = RACEgroup, fill = RACEgroup) +
#  geom_bar(position = "dodge") +
#  scale_fill_hue() +
#  labs(x = "Race", y = "Count", title = "Enrolled vs Not Enrolled in Clinical Trials", fill = "Race") +
#  theme_classic() +
#  facet_wrap(vars(COVCLINTRIAL))
# 
# ggplot(dft1) +
#  aes(x = COVCLINTRIAL, fill = RACEgroup) +
#  geom_bar(position = "dodge") +
#  scale_fill_hue() +
#  labs(x = "Enrolled/Not-Enrolled", y = "Count", title = "Enrolled vs Not Enrolled in Clinical Trials by Race", fill = "Race") +
#  theme_minimal() +
#  theme(legend.position = "none") +
#  facet_wrap(vars(RACEgroup))
# 
# ggplot(dft1) +
#  aes(x = COVCLINTRIAL, fill = RACEgroup) +
#  geom_bar(position = "dodge") +
#  scale_fill_hue() +
#  labs(x = "Enrolled/Not-Enrolled", y = "Count", title = "Enrolled vs Not Enrolled in Clinical Trials by Race", fill = "Race") +
#  theme_classic() +
#  theme(legend.position = "none") +
#  facet_wrap(vars(RACEgroup))
# 
# dft1 %>%
#  filter(!(RACEgroup %in% c("Other", "UTD"))) %>%
#  ggplot() +
#  aes(x = COVCLINTRIAL, fill = RACEgroup) +
#  geom_bar(position = "dodge") +
#  scale_fill_hue() +
#  labs(x = "Enrolled/Not-Enrolled", y = "Count", title = "Enrolled vs Not Enrolled in Clinical Trials by Race", fill = "Race") +
#  ggthemes::theme_fivethirtyeight() +
#  theme(legend.position = "none") +
#  facet_wrap(vars(RACEgroup))
# 
# dft1 %>%
#  filter(!(RACEgroup %in% c("Other", "UTD"))) %>%
#  ggplot() +
#  aes(x = COVCLINTRIAL, fill = RACEgroup, group = RACEgroup) +
#  geom_bar(position = "dodge") +
#  scale_fill_hue() +
#  labs(x = "Enrolled/Not-Enrolled", y = "Count", title = "Enrolled vs Not Enrolled in Clinical Trials by Race", fill = " ") +
#  ggthemes::theme_fivethirtyeight()
# ```

